services:
  stalker-db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: stalker-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "MinistraDb2026Q7v9K2m4"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "stalker_db"
    command:
      - "--sql-mode=NO_ENGINE_SUBSTITUTION"
    volumes:
      - stalker_mysql:/var/lib/mysql
    networks:
      - stalker-net

  stalker-portal:
    image: ghcr.io/neilruffell/mac-portal:master
    platform: linux/amd64
    container_name: stalker-portal
    restart: unless-stopped
    depends_on:
      - stalker-db
    environment:
      STALKER_DB_HOST: "stalker-db"
      STALKER_DB_NAME: "stalker_db"
      STALKER_DB_PASSWORD: "MinistraDb2026Q7v9K2m4"
      DEBIAN_FRONTEND: "noninteractive"
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
      LANGUAGE: "en"
    ports:
      - "34080:88"
    volumes:
    #   - type: bind
    #     source: /mnt/zfs-01-ssd/apps/ministra/custom-c/tv.js
    #     target: /var/www/html/stalker_portal/c/tv.js
    #     bind:
    #       create_host_path: false
      - type: bind
        source: /mnt/zfs-01-ssd/apps/ministra/custom-c/epg.js
        target: /var/www/html/stalker_portal/c/epg.js
        bind:
          create_host_path: false
    #   - type: bind
    #     source: /mnt/zfs-01-ssd/apps/ministra/custom-c/player.js
    #     target: /var/www/html/stalker_portal/c/player.js
    #     bind:
    #       create_host_path: false
    #   - type: bind
    #     source: /mnt/zfs-01-ssd/apps/ministra/custom-c/template
    #     target: /var/www/html/stalker_portal/c/template
    #     bind:
    #       create_host_path: false
    networks:
      - stalker-net

networks:
  stalker-net:
    name: stalker-net
    driver: bridge

volumes:
  stalker_mysql:
